### ISSUE TITLE
what is the different bettween dispatch with your overload function module?

### ISSUE THREAD

**Issue by ghost** [HashSplat/overload_function#1]

**Comment by justengel** [comment]
I do not know what "dispatch" you are asking about. Can you provide more information or a code example?

**Comment by upcFrost** [comment]
I think he means `@singledispatch` from the standard lib

https://docs.python.org/3/library/functools.html#functools.singledispatch

**Comment by justengel** [comment]
Looks like singledispatch does the same thing. You probably just want to use singledispatch.
